os:
  - linux

language: node_js
node_js:
  - '6'

cache:
  directories:
    - node_modules

script: "npm run lint && npm run test:ci"
  directories:cript: "npm run lint && npm run test:ci"
after_success: npm run coveralls
